/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontAddApiTokenDto } from '../model/models';
import { ZidiumWebServiceFrontApiTokenDto } from '../model/models';
import { ZidiumWebServiceFrontApiTokenListDto } from '../model/models';
import { ZidiumWebServiceFrontUpdateApiTokenDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApiTokensServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param zidiumWebServiceFrontAddApiTokenDto 
     */
    add(zidiumWebServiceFrontAddApiTokenDto?: ZidiumWebServiceFrontAddApiTokenDto, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param userId 
     */
    getAll(userId?: number, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontApiTokenListDto>;

    /**
     * 
     * 
     * @param id 
     */
    getById(id: number, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontApiTokenDto>;

    /**
     * 
     * 
     * @param id 
     * @param zidiumWebServiceFrontUpdateApiTokenDto 
     */
    update(id: number, zidiumWebServiceFrontUpdateApiTokenDto?: ZidiumWebServiceFrontUpdateApiTokenDto, extraHttpRequestParams?: any): Observable<{}>;

}
