/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ZidiumWebServiceFrontAddComponentEventTypeDto } from '../model/models';
import { ZidiumWebServiceFrontComponentEventTypeDto } from '../model/models';
import { ZidiumWebServiceFrontComponentEventTypeListDto } from '../model/models';
import { ZidiumWebServiceFrontUpdateComponentEventTypeDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ComponentEventTypesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    _delete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param zidiumWebServiceFrontAddComponentEventTypeDto 
     */
    add(zidiumWebServiceFrontAddComponentEventTypeDto?: ZidiumWebServiceFrontAddComponentEventTypeDto, extraHttpRequestParams?: any): Observable<number>;

    /**
     * Получение типов событий компонентов с делением на страницы
     * 
     * @param search Строка для поиска
     * @param pageNumber Номер страницы, нумерация с 0
     * @param pageSize Размер страницы
     * @param sortDesc Сортировка по убыванию
     */
    getAll(search?: string, pageNumber?: number, pageSize?: number, sortDesc?: boolean, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentEventTypeListDto>;

    /**
     * 
     * 
     * @param id 
     */
    getById(id: number, extraHttpRequestParams?: any): Observable<ZidiumWebServiceFrontComponentEventTypeDto>;

    /**
     * 
     * 
     * @param name 
     * @param id 
     */
    nameExists(name: string, id?: number, extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     * @param id 
     * @param zidiumWebServiceFrontUpdateComponentEventTypeDto 
     */
    update(id: number, zidiumWebServiceFrontUpdateComponentEventTypeDto?: ZidiumWebServiceFrontUpdateComponentEventTypeDto, extraHttpRequestParams?: any): Observable<{}>;

}
