// Generates src/environments/environment.ts from .env (or process.env).
//
// The backend URL is kept out of git (public repo): the generated file is
// gitignored and rebuilt from local config on install/start/build/test.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

import { loadDotEnv } from './load-dotenv.mjs';

const fileEnv = loadDotEnv();
const apiBaseUrl = process.env.API_BASE_URL ?? fileEnv.API_BASE_URL ?? '';
const production = process.env.NODE_ENV === 'production';

const out = join(process.cwd(), 'src', 'environments', 'environment.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/gen-env.mjs — do not edit, do not commit.
// Values come from .env (see .env.example). Regenerate with \`npm run gen:env\`.
export const environment = {
  production: ${production},
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
} as const;
`,
);

console.log(`[gen:env] wrote ${out} (apiBaseUrl=${apiBaseUrl || '<empty>'})`);
if (!apiBaseUrl) {
  console.warn('[gen:env] API_BASE_URL is empty — set it in .env for live API calls.');
}
