/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Общие права, не зависящие от компонента
 */
export type CommonPermission = 'DictionariesRead' | 'DictionariesWrite' | 'SelfUserRead' | 'SelfUserWrite' | 'AllUsersRead' | 'AllUsersWrite' | 'UserGroupsRead' | 'UserGroupsWrite' | 'SelfApiTokensRead' | 'SelfApiTokensWrite' | 'AllApiTokensRead' | 'AllApiTokensWrite' | 'SubscriptionsRead' | 'SubscriptionsWrite' | 'RolesRead' | 'RolesWrite';

export const CommonPermission = {
    DictionariesRead: 'DictionariesRead' as CommonPermission,
    DictionariesWrite: 'DictionariesWrite' as CommonPermission,
    SelfUserRead: 'SelfUserRead' as CommonPermission,
    SelfUserWrite: 'SelfUserWrite' as CommonPermission,
    AllUsersRead: 'AllUsersRead' as CommonPermission,
    AllUsersWrite: 'AllUsersWrite' as CommonPermission,
    UserGroupsRead: 'UserGroupsRead' as CommonPermission,
    UserGroupsWrite: 'UserGroupsWrite' as CommonPermission,
    SelfApiTokensRead: 'SelfApiTokensRead' as CommonPermission,
    SelfApiTokensWrite: 'SelfApiTokensWrite' as CommonPermission,
    AllApiTokensRead: 'AllApiTokensRead' as CommonPermission,
    AllApiTokensWrite: 'AllApiTokensWrite' as CommonPermission,
    SubscriptionsRead: 'SubscriptionsRead' as CommonPermission,
    SubscriptionsWrite: 'SubscriptionsWrite' as CommonPermission,
    RolesRead: 'RolesRead' as CommonPermission,
    RolesWrite: 'RolesWrite' as CommonPermission
};

