/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CurrentUserPermissions { 
    users: boolean;
    userGroups: boolean;
    apiTokens: boolean;
    roles: boolean;
    otherDictionaries: boolean;
}

