/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type IndicatorDataType = 'String' | 'Number' | 'Boolean' | 'DateTime' | 'Json';

export const IndicatorDataType = {
    String: 'String' as IndicatorDataType,
    Number: 'Number' as IndicatorDataType,
    Boolean: 'Boolean' as IndicatorDataType,
    DateTime: 'DateTime' as IndicatorDataType,
    Json: 'Json' as IndicatorDataType
};

