/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Права, зависящие от компонента
 */
export type PermissionByComponent = 'ComponentsRead' | 'ComponentsWrite' | 'IndicatorsRead' | 'IndicatorsWrite' | 'IndicatorsSendValue' | 'ComponentEventsRead' | 'ComponentEventsSend' | 'PeriodicChecksRead' | 'PeriodicChecksWrite';

export const PermissionByComponent = {
    ComponentsRead: 'ComponentsRead' as PermissionByComponent,
    ComponentsWrite: 'ComponentsWrite' as PermissionByComponent,
    IndicatorsRead: 'IndicatorsRead' as PermissionByComponent,
    IndicatorsWrite: 'IndicatorsWrite' as PermissionByComponent,
    IndicatorsSendValue: 'IndicatorsSendValue' as PermissionByComponent,
    ComponentEventsRead: 'ComponentEventsRead' as PermissionByComponent,
    ComponentEventsSend: 'ComponentEventsSend' as PermissionByComponent,
    PeriodicChecksRead: 'PeriodicChecksRead' as PermissionByComponent,
    PeriodicChecksWrite: 'PeriodicChecksWrite' as PermissionByComponent
};

