/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип источника причины
 */
export type ReasonSourceType = 'ChildComponent' | 'Indicator' | 'ComponentEvent';

export const ReasonSourceType = {
    ChildComponent: 'ChildComponent' as ReasonSourceType,
    Indicator: 'Indicator' as ReasonSourceType,
    ComponentEvent: 'ComponentEvent' as ReasonSourceType
};

