/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип объекта подписки
 */
export type SubscriptionObjectType = 'Indicator' | 'Component' | 'ComponentType' | 'IndicatorType';

export const SubscriptionObjectType = {
    Indicator: 'Indicator' as SubscriptionObjectType,
    Component: 'Component' as SubscriptionObjectType,
    ComponentType: 'ComponentType' as SubscriptionObjectType,
    IndicatorType: 'IndicatorType' as SubscriptionObjectType
};

