/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentEventTypeDto } from './zidium-web-service-front-component-event-type-dto';


export interface ZidiumWebServiceFrontComponentEventTypeListDto { 
    items: Array<ZidiumWebServiceFrontComponentEventTypeDto>;
    canAdd: boolean;
}

