/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontSelectorDto } from './zidium-web-service-front-selector-dto';
import { ZidiumWebServiceFrontTokenCommonPermissionItem } from './zidium-web-service-front-token-common-permission-item';
import { ZidiumWebServiceFrontTokenPermissionByComponentItem } from './zidium-web-service-front-token-permission-by-component-item';
import { ZidiumWebServiceFrontComponentSelectorDto } from './zidium-web-service-front-component-selector-dto';


export interface ZidiumWebServiceFrontApiTokenDto { 
    id: number;
    token: string;
    name: string;
    user: ZidiumWebServiceFrontSelectorDto;
    createdAt: string;
    commonPermissions: Array<ZidiumWebServiceFrontTokenCommonPermissionItem>;
    permissionsByComponent: Array<ZidiumWebServiceFrontTokenPermissionByComponentItem>;
    accessComponent: ZidiumWebServiceFrontComponentSelectorDto;
    canEdit: boolean;
}

