/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontUserGroupListItemDto } from './zidium-web-service-front-user-group-list-item-dto';


export interface ZidiumWebServiceFrontUserGroupListDto { 
    items: Array<ZidiumWebServiceFrontUserGroupListItemDto>;
    canAdd: boolean;
}

