/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontCategoryDto } from './zidium-web-service-front-category-dto';


export interface ZidiumWebServiceFrontCategoryListDto { 
    items: Array<ZidiumWebServiceFrontCategoryDto>;
    canAdd: boolean;
}

