/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTypeDto } from './zidium-web-service-front-component-type-dto';


export interface ZidiumWebServiceFrontComponentTypeListDto { 
    items: Array<ZidiumWebServiceFrontComponentTypeDto>;
    canAdd: boolean;
}

