/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontApiTokenListItemDto } from './zidium-web-service-front-api-token-list-item-dto';


export interface ZidiumWebServiceFrontApiTokenListDto { 
    items: Array<ZidiumWebServiceFrontApiTokenListItemDto>;
    canAdd: boolean;
    canWorkWithAllTokens: boolean;
}

