/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontIndicatorTypeDto } from './zidium-web-service-front-indicator-type-dto';


export interface ZidiumWebServiceFrontIndicatorTypeListDto { 
    items: Array<ZidiumWebServiceFrontIndicatorTypeDto>;
    canAdd: boolean;
}

