/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionByComponent } from './permission-by-component';


export interface ZidiumWebServiceFrontRolePermissionByComponentItem { 
    permissionId: PermissionByComponent;
    permissionName: string;
    hasPermission: boolean;
    enabled: boolean;
}
export namespace ZidiumWebServiceFrontRolePermissionByComponentItem {
}


