/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReasonSourceType } from './reason-source-type';
import { IndicatorDataType } from './indicator-data-type';
import { ZidiumCoreApiStatus } from './zidium-core-api-status';


export interface ZidiumWebServiceFrontComponentHealthReasonDto { 
    id: number;
    displayName: string;
    sourceType: ReasonSourceType;
    canExpand: boolean;
    isLink: boolean;
    damage: number;
    status: ZidiumCoreApiStatus;
    indicatorDataType?: IndicatorDataType;
    indicatorValue?: any | null;
    indicatorMessage?: string | null;
}
export namespace ZidiumWebServiceFrontComponentHealthReasonDto {
}


