/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTotalSubscriptionItemDto } from './zidium-web-service-front-component-total-subscription-item-dto';


export interface ZidiumWebServiceFrontComponentTotalSubscriptionDto { 
    channelId: number;
    channelName: string;
    data?: ZidiumWebServiceFrontComponentTotalSubscriptionItemDto;
    canEdit: boolean;
}

