/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZidiumWebServiceFrontApiTokenListItemDto { 
    id: number;
    name: string;
    createdAt: string;
    userId: number;
    userName: string;
    canEdit: boolean;
    canDelete: boolean;
}

