/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontUserListItemDto } from './zidium-web-service-front-user-list-item-dto';


export interface ZidiumWebServiceFrontUserListDto { 
    items: Array<ZidiumWebServiceFrontUserListItemDto>;
    canAdd: boolean;
}

