/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommonPermission } from './common-permission';
import { PermissionByComponent } from './permission-by-component';


export interface ZidiumWebServiceFrontEditRoleDto { 
    name: string;
    commonPermissions: Array<CommonPermission>;
    permissionsByComponent: Array<PermissionByComponent>;
}

