/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentLinkDto } from './zidium-web-service-front-component-link-dto';


export interface ZidiumWebServiceFrontComponentLinksDto { 
    incomingLinks: Array<ZidiumWebServiceFrontComponentLinkDto>;
    outgoingLinks: Array<ZidiumWebServiceFrontComponentLinkDto>;
}

