/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontDefaultSubscriptionDto } from './zidium-web-service-front-default-subscription-dto';
import { ZidiumWebServiceFrontObjectSubscriptionDto } from './zidium-web-service-front-object-subscription-dto';


export interface ZidiumWebServiceFrontComponentChannelSubscriptionDto { 
    channelName: string;
    userGroupId: number;
    userGroupName: string;
    componentTypeId: number;
    componentSubscription?: ZidiumWebServiceFrontObjectSubscriptionDto;
    componentTypeSubscription?: ZidiumWebServiceFrontObjectSubscriptionDto;
    parentComponentSubscription?: ZidiumWebServiceFrontObjectSubscriptionDto;
    defaultSubscription?: ZidiumWebServiceFrontDefaultSubscriptionDto;
}

