/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumCoreApiStatus } from './zidium-core-api-status';


export interface ZidiumWebServiceFrontComponentHealthHistoryItemDto { 
    id: number;
    startedAt: string;
    finishedAt?: string | null;
    status: ZidiumCoreApiStatus;
    health: number;
}
export namespace ZidiumWebServiceFrontComponentHealthHistoryItemDto {
}


