/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontRoleCommonPermissionItem } from './zidium-web-service-front-role-common-permission-item';
import { ZidiumWebServiceFrontRolePermissionByComponentItem } from './zidium-web-service-front-role-permission-by-component-item';


export interface ZidiumWebServiceFrontRoleDto { 
    id: number;
    canEdit: boolean;
    canDelete: boolean;
    name: string;
    commonPermissions: Array<ZidiumWebServiceFrontRoleCommonPermissionItem>;
    permissionsByComponent: Array<ZidiumWebServiceFrontRolePermissionByComponentItem>;
}

