/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ZidiumWebServiceFrontComponentSelectorTreeItemDto { 
    id: number;
    displayName: string;
    fullName: Array<string>;
    canExpand: boolean;
    children: Array<ZidiumWebServiceFrontComponentSelectorTreeItemDto>;
}

