/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontUserGroupChannelSettingItemDto } from './zidium-web-service-front-user-group-channel-setting-item-dto';
import { ZidiumWebServiceFrontUserGroupUserItemDto } from './zidium-web-service-front-user-group-user-item-dto';
import { ZidiumWebServiceFrontComponentSelectorDto } from './zidium-web-service-front-component-selector-dto';


export interface ZidiumWebServiceFrontUserGroupDto { 
    id: number;
    canEdit: boolean;
    canDelete: boolean;
    name: string;
    priority: number;
    channelSettings: Array<ZidiumWebServiceFrontUserGroupChannelSettingItemDto>;
    users: Array<ZidiumWebServiceFrontUserGroupUserItemDto>;
    accessComponent: ZidiumWebServiceFrontComponentSelectorDto;
}

