/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontHealthAndStatusDto } from './zidium-web-service-front-health-and-status-dto';
import { ZidiumWebServiceFrontComponentStatusHistoryItemDto } from './zidium-web-service-front-component-status-history-item-dto';


export interface ZidiumWebServiceFrontComponentHealthDto { 
    healthAndStatus?: ZidiumWebServiceFrontHealthAndStatusDto;
    items: Array<ZidiumWebServiceFrontComponentStatusHistoryItemDto>;
}

