/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTreeIndicatorDto } from './zidium-web-service-front-component-tree-indicator-dto';
import { ZidiumWebServiceFrontComponentTreeEventsDto } from './zidium-web-service-front-component-tree-events-dto';
import { ZidiumWebServiceFrontComponentTreeItemDto } from './zidium-web-service-front-component-tree-item-dto';


export interface ZidiumWebServiceFrontComponentTreeItemExpandedDto { 
    readonly childComponents: Array<ZidiumWebServiceFrontComponentTreeItemDto>;
    readonly indicators: Array<ZidiumWebServiceFrontComponentTreeIndicatorDto>;
    events?: ZidiumWebServiceFrontComponentTreeEventsDto;
}

