/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontSelectorDto } from './zidium-web-service-front-selector-dto';


export interface ZidiumWebServiceFrontUserInGroupItemDto { 
    userGroup: ZidiumWebServiceFrontSelectorDto;
    role: ZidiumWebServiceFrontSelectorDto;
}

