/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommonPermission } from './common-permission';
import { PermissionByComponent } from './permission-by-component';


export interface ZidiumWebServiceFrontAddApiTokenDto { 
    /**
     * Id пользователя, которому добавляется токен (null - текущий пользователь)
     */
    userId?: number | null;
    name: string;
    commonPermissions: Array<CommonPermission>;
    permissionsByComponent: Array<PermissionByComponent>;
    accessComponentId: number;
}

