/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusSettingsDto } from './status-settings-dto';
import { ZidiumCoreApiPropertyDto } from './zidium-core-api-property-dto';


export interface ZidiumWebServiceFrontComponentSettingsDto { 
    systemName: string;
    displayName: string;
    isEnabled: boolean;
    weight: number;
    componentTypeId: number;
    statusSettings: StatusSettingsDto;
    properties: Array<ZidiumCoreApiPropertyDto>;
    id: number;
    parentComponentId?: number | null;
    componentTypeName: string;
}

