/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontPeriodicCheckTypeDto } from './zidium-web-service-front-periodic-check-type-dto';


export interface ZidiumWebServiceFrontPeriodicCheckTypeListDto { 
    items: Array<ZidiumWebServiceFrontPeriodicCheckTypeDto>;
    canAdd: boolean;
}

