/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontComponentTreeItemPermissions } from './zidium-web-service-front-component-tree-item-permissions';
import { ZidiumCoreApiStatus } from './zidium-core-api-status';
import { ZidiumWebServiceFrontComponentTreeItemExpandedDto } from './zidium-web-service-front-component-tree-item-expanded-dto';


export interface ZidiumWebServiceFrontComponentTreeItemDto { 
    id: number;
    displayName: string;
    status?: ZidiumCoreApiStatus;
    health?: number | null;
    statusStartedAt?: string | null;
    isLink: boolean;
    isEnabled: boolean;
    canExpand: boolean;
    permissions: ZidiumWebServiceFrontComponentTreeItemPermissions;
    expanded?: ZidiumWebServiceFrontComponentTreeItemExpandedDto;
}
export namespace ZidiumWebServiceFrontComponentTreeItemDto {
}


