/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ZidiumCoreApiStatus = 'Unknown' | 'Success' | 'Warning' | 'Danger' | 'Critical' | 'Fatal';

export const ZidiumCoreApiStatus = {
    Unknown: 'Unknown' as ZidiumCoreApiStatus,
    Success: 'Success' as ZidiumCoreApiStatus,
    Warning: 'Warning' as ZidiumCoreApiStatus,
    Danger: 'Danger' as ZidiumCoreApiStatus,
    Critical: 'Critical' as ZidiumCoreApiStatus,
    Fatal: 'Fatal' as ZidiumCoreApiStatus
};

