/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumWebServiceFrontUserContactItemDto } from './zidium-web-service-front-user-contact-item-dto';
import { ZidiumWebServiceFrontUserInGroupItemDto } from './zidium-web-service-front-user-in-group-item-dto';
import { ZidiumWebServiceFrontTimeZoneSelectorDto } from './zidium-web-service-front-time-zone-selector-dto';


export interface ZidiumWebServiceFrontUserDto { 
    id: number;
    canEdit: boolean;
    canDelete: boolean;
    name: string;
    displayName: string;
    timeZone: ZidiumWebServiceFrontTimeZoneSelectorDto;
    contacts: Array<ZidiumWebServiceFrontUserContactItemDto>;
    groups: Array<ZidiumWebServiceFrontUserInGroupItemDto>;
    canEditName: boolean;
    canEditGroups: boolean;
}

