/**
 * Zidium Front
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZidiumCoreApiStatus } from './zidium-core-api-status';


export interface ZidiumWebServiceFrontComponentHealthAtMomentDto { 
    health: number;
    status: ZidiumCoreApiStatus;
    statusStartedAt: string;
    healthHistoryId: number;
    statusHistoryId: number;
}
export namespace ZidiumWebServiceFrontComponentHealthAtMomentDto {
}


